(function(config){var e=navigator.userAgent.toLowerCase(),w=window,B=document;function C(a){return-1!==e.indexOf(a)}
var aa=C("ucbrowser"),ba=C("micromessenger"),ca=C("mqqbrowser"),E="ActiveXObject"in w,da=E&&!w.XMLHttpRequest,ea=E&&!B.querySelector,fa=E&&!B.addEventListener,ga=E&&C("ie 9"),ha=E&&C("rv:11"),ja=w.navigator&&w.navigator.msPointerEnabled&&!!w.navigator.msMaxTouchPoints,ka=ja||C("touch")||"ontouchstart"in B,la=C("webkit"),chrome=C("chrome"),ma=C("firefox"),na=C("android"),oa=-1!==e.search(/android( |\/)4\./),pa=-1!==e.search(/android [23]/),qa=C("windows phone"),ra="devicePixelRatio"in w&&1<w.devicePixelRatio||
"matchMedia"in w&&w.matchMedia("(min-resolution:144dpi)")&&w.matchMedia("(min-resolution:144dpi)").matches,sa=C("ipad;"),ta=sa&&ra,ua=C("ipod touch;"),va=C("iphone;"),wa=va||sa||ua,xa=C("safari"),ya=(C(" os 7")||C(" os 8"))&&wa,G=na||wa||qa||C("mobile")||"undefined"!==typeof orientation,za=B.documentElement,Aa=E&&"transition"in za.style,Ba=!!B.createElementNS&&!!B.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,Ca=!!B.createElement("canvas").getContext,Da="WebKitCSSMatrix"in w&&
"m11"in new window.WebKitCSSMatrix,Ea="MozPerspective"in za.style,Fa="OTransition"in za.style,Ga=Aa||Da||Ea||Fa,Ha=C("windows nt"),Ia=!G&&Ha&&-1!==e.search(/nt [1-5]\./),Ja=C("baidubrowser"),Ka;
if(!(Ka=!Ca)){var La;if(!(La=ga)){var Ma;if(!(Ma=na&&!(oa&&(-1!==e.search(/m351|firefox/)?0:ba&&ca?-1===e.search(/hm note|gt-|m1 note/):C("gt-n710")&&-1!==e.search(/android( |\/)4\.1/)?0:-1!==e.search(/ucbrowser\/((9\.[0-5]\.)|(10\.))/)?-1===e.search(/huawei( p6|h30)/):C("baidubrowser")?-1===e.search(/hm201|sm-g900/):-1!==e.search(/lbbrowser|360|liebao|oupeng|mqqbrowser|sogou|micromessenger|chrome/)||!C("ucbrowser")&&-1!==e.search(/sm-n900|(gt-(n710|i95|p[67]))|(mi( [1-4]|-one))|(huawei( p6|_c8813|h30| g750))|lenovo k900|coolpad_9150/))))){var Na;
if(Na=va){var Oa=screen.width;Na=!(ya&&(aa||ba?!(375<Oa):xa))}Ma=Na||ua||ta||qa||G&&ma||Ha&&C("version")}La=Ma}Ka=La}var Pa=Ka,Qa=!1;try{Qa="undefined"!==typeof w.localStorage}catch(Ra){}var Sa=void 0!==config[8]?config[8]:!0,Ta=void 0!==config[9]?config[9]:!0;
config.f={size:100,uq:C("macintosh"),kp:Ja,PK:ca,af:E,ad:da,Mk:ea,zc:fa,aF:E&&!ha,iI:la,Km:Qa,vd:na,eJ:pa,vn:aa,chrome:chrome,zv:ma,gK:Aa,jI:Da,FJ:Ea,IK:Fa,SC:Ga,ca:G,FK:G&&la,LF:G&&Da,EK:G&&w.opera,kF:wa,hc:ka,uw:ja,hK:ga,ma:ra,jg:Ba,Ok:Ca,mK:!!w.JI,Pw:Pa,Qg:Sa&&!Pa&&!Ia,mq:Ta&&!!w.WebSocket&&!Ja&&!!w.Worker,Ow:!Ba&&G&&Ca};var w=window,H="http map anip layers overlay0 brender mrender".split(" ");config.dd="main";config.f.hc&&(H+=",touch",config.dd+="t");config.f.ca||(H+=",mouse",config.dd+="m");H+=",crender";config.dd+="c";config.f.Qg&&(config.dd+="v",H+=",vectorlayer,overlay",H+=",vp",config.dd+="p");config[7]&&(H+=","+config[7],config.dd+=config[7].replace(",","").replace(eval("/AMap./gi"),""));H+=",sync";config.oy=H.split(",");window.AMap=window.AMap||{};window.AMap.Kf="1.3.10.1";var Ua=window.AMap.zr={},Va=config[2].split(",")[0],Wa=Va+"/theme/v"+config[4]+"/style1.3.10.1.css",Xa=document.head||document.getElementsByTagName("head")[0];if(Xa){var Ya=document.createElement("link");Ya.setAttribute("rel","stylesheet");Ya.setAttribute("type","text/css");Ya.setAttribute("href",Wa);Xa.insertBefore(Ya,Xa.firstChild)}else document.write("<link rel='stylesheet' href='"+Wa+"'/>");
function Za(){var a=$a,b=document,c=b.createElement("script");c.charset="utf-8";c.src=a;(a=b.body||Xa)&&a.appendChild(c)}var ab=(new Date).getTime();Ua.__load__=function(a){a(config,ab);delete Ua.__load__};try{if(window.localStorage){var I=window.localStorage["_AMap_"+config.dd],bb=!1;I?(I=JSON.parse(I),I.version===window.AMap.Kf?(eval(I.script),Ua.loaded=!0):bb=!0):bb=!0;if(bb)for(var cb in window.localStorage)window.localStorage.hasOwnProperty(cb)&&0===cb.indexOf("_AMap_")&&window.localStorage.removeItem(cb)}}catch(db){}
if(!Ua.loaded){for(var $a=Va+"/maps/main?v="+config[4]+"&key="+config[0]+"&m="+config.oy.join(",")+"&vrs=1.3.10.1",eb=document.getElementsByTagName("script"),fb,J=0;J<eb.length;J+=1)if(0===eb[J].src.indexOf(Va.split(":")[1]+"/maps?")){fb=eb[J];break}config[5]||fb&&fb.async?Za():(document.write('<script id="amap_main_js" src=\''+$a+"' type='text/javascript'>\x3c/script>"),document.getElementById("amap_main_js")||Za());delete config.oy};
})(["1c22ed8fcc81436197faf632aaed0ddb",[120.856805,30.675593,122.247149,31.872716,121.472644,31.231706],"http://webapi.amap.com",1,"1.3",null,"310000","",true,true])